// Starting data for the state guides: minimum auto insurance requirements researched on
// 2026-10-03, then confirmed state by state against official sources (state statutes and
// Department of Insurance / DMV pages). Each state is imported unchecked; an admin ticks
// "Facts checked" (one by one, or with "Tick all confirmed states") before it can be published.
//
// "Rejectable" coverages (included by default but the driver can decline in writing) are
// marked not required and explained in the note.

export const RESEARCHED_ON = "2026-10-03";

export type StateResearch = {
  bi: number; // bodily injury per person ($); 0 = no bodily injury requirement
  ba: number; // bodily injury per accident
  pd: number; // property damage
  noFault: boolean;
  pip: boolean;
  pipMin: number | null;
  um: boolean;
  uim: boolean;
  medPay: boolean;
  optional?: boolean; // insurance itself not required (financial responsibility instead)
  note: string; // shown on the public page
  sourceUrl: string;
  confidence: "high" | "medium";
  caveat?: string; // admin-only: where sources disagreed
};

export const STATE_RESEARCH: Record<string, StateResearch> = {
  AK: { bi: 50000, ba: 100000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Alaska has some of the highest minimum limits in the country. Uninsured and underinsured motorist coverage must be offered but can be declined.", sourceUrl: "https://dmv.alaska.gov/driver-services-adjudication/mandatory-insurance/", confidence: "high" },
  AL: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured motorist coverage must be offered and is included unless you reject it in writing.", sourceUrl: "https://www.revenue.alabama.gov/tax-types/mandatory-liability-insurance/", confidence: "high" },
  AR: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Insurers must include $5,000 of personal injury protection and offer uninsured motorist coverage, but you can reject both in writing, so only liability is strictly required.", sourceUrl: "https://insurance.arkansas.gov/documents/automobile-insurance-brochure/", confidence: "high" },
  AZ: { bi: 25000, ba: 50000, pd: 15000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Arizona raised its minimums to 25/50/15 for policies issued or renewed on or after July 1, 2020. Uninsured and underinsured motorist coverage must be offered.", sourceUrl: "https://www.azleg.gov/ars/28/04009.htm", confidence: "high" },
  CA: { bi: 30000, ba: 60000, pd: 15000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "California raised its minimums from 15/30/5 to 30/60/15 on January 1, 2025, the first increase since 1967. The California Low Cost Auto program has lower limits for eligible low-income drivers.", sourceUrl: "https://www.dmv.ca.gov/portal/vehicle-registration/insurance-requirements/", confidence: "high" },
  CO: { bi: 25000, ba: 50000, pd: 15000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Policies include $5,000 of medical payments coverage unless you reject it. Uninsured and underinsured motorist coverage is included unless you reject it in writing.", sourceUrl: "https://doi.colorado.gov/types-of-insurance/auto-insurance", confidence: "high" },
  CT: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "Uninsured and underinsured motorist coverage of at least 25/50 is mandatory. A $50,000 combined single limit can also meet the liability requirement.", sourceUrl: "https://portal.ct.gov/cid/consumer-information-center/auto-insurance", confidence: "high" },
  DC: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of $25,000/$50,000 for injuries and $5,000 for property damage is mandatory. Personal injury protection must be offered but is optional.", sourceUrl: "https://code.dccouncil.gov/us/dc/council/code/sections/31-2406", confidence: "high", caveat: "D.C. Law 26-155 amends the requirement (D.C. Code 31-2406) effective October 1, 2027. Recheck the limits then." },
  DE: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: true, pipMin: 15000, um: false, uim: false, medPay: false, note: "Delaware requires personal injury protection of $15,000 per person and $30,000 per accident, but it doesn't limit lawsuits, so it isn't a true no-fault state.", sourceUrl: "https://dmv.de.gov/VehicleServices/registration/index.shtml?dc=ve_reg_insurance", confidence: "high" },
  FL: { bi: 0, ba: 0, pd: 10000, noFault: true, pip: true, pipMin: 10000, um: false, uim: false, medPay: false, note: "Bodily injury liability isn't required for most drivers, but 10/20 can be required after certain crashes, and after a DUI conviction drivers must carry 100/300/50 and file an FR-44 for three years.", sourceUrl: "https://www.flsenate.gov/Laws/Statutes/2026/627.736", confidence: "high" },
  GA: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured motorist coverage is included unless you reject it in writing.", sourceUrl: "https://oci.georgia.gov/insurance-resources/auto", confidence: "high" },
  HI: { bi: 40000, ba: 80000, pd: 20000, noFault: true, pip: true, pipMin: 10000, um: false, uim: false, medPay: false, note: "Hawaii doubled its minimums from 20/40/10 to 40/80/20 for policies issued or renewed on or after January 1, 2026. $10,000 of personal injury protection is still required.", sourceUrl: "https://cca.hawaii.gov/ins/files/2023/05/Auto-Minimum-Limits-FAQs.pdf", confidence: "high" },
  IA: { bi: 20000, ba: 40000, pd: 15000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Iowa has some of the lowest minimums in the country. Uninsured and underinsured motorist coverage must be offered but can be rejected in writing.", sourceUrl: "https://iid.iowa.gov/consumers/insurance/auto", confidence: "high" },
  ID: { bi: 25000, ba: 50000, pd: 15000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured and underinsured motorist coverage must be offered and can be rejected in writing.", sourceUrl: "https://legislature.idaho.gov/statutesrules/idstat/Title49/T49CH1/SECT49-117/", confidence: "high" },
  IL: { bi: 25000, ba: 50000, pd: 20000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of 25/50 is mandatory. Underinsured motorist coverage is only required when you buy uninsured motorist limits above the minimum.", sourceUrl: "https://idoi.illinois.gov/consumers/consumerinsurance/auto-insurance-shopping-guide.html", confidence: "high" },
  IN: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured motorist coverage (25/50 for injuries, $25,000 for property) and underinsured motorist coverage ($50,000) are included unless you reject them in writing.", sourceUrl: "https://www.in.gov/idoi/consumer-services/types-of-insurance/auto-insurance/", confidence: "high" },
  KS: { bi: 25000, ba: 50000, pd: 25000, noFault: true, pip: true, pipMin: 4500, um: true, uim: true, medPay: false, note: "Kansas requires personal injury protection, including $4,500 for medical expenses and $4,500 for rehabilitation, plus uninsured motorist coverage that includes underinsured protection. The property damage minimum is $25,000.", sourceUrl: "https://ksrevisor.gov/statutes/chapters/ch40/040_031_0007.html", confidence: "high" },
  KY: { bi: 25000, ba: 50000, pd: 25000, noFault: true, pip: true, pipMin: 10000, um: false, uim: false, medPay: false, note: "Kentucky is a choice no-fault state: $10,000 of personal injury protection applies unless you file a form rejecting no-fault to keep full rights to sue. A $60,000 combined single limit also meets the liability requirement.", sourceUrl: "https://insurance.ky.gov/ppc/Documents/Bulletin%202026-04%20No%20Fault%20Rejection.pdf", confidence: "high" },
  LA: { bi: 15000, ba: 30000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Louisiana has the lowest per-person minimum in the country. Under its \"no pay, no play\" law, uninsured drivers can't recover the first $15,000 of injury costs or $25,000 of property damage after a crash.", sourceUrl: "https://www.ldi.la.gov/docs/default-source/documents/publicaffairs/consumerpublications/auto-insurance-guide.pdf?sfvrsn=15", confidence: "high" },
  MA: { bi: 25000, ba: 50000, pd: 30000, noFault: true, pip: true, pipMin: 8000, um: true, uim: false, medPay: false, note: "Massachusetts raised its minimums from 20/40/5 to 25/50/30 for policies issued or renewed on or after July 1, 2025, the first increase since 1988. Personal injury protection of $8,000 and uninsured motorist coverage of 25/50 are required.", sourceUrl: "https://www.mass.gov/info-details/basics-of-auto-insurance", confidence: "high" },
  MD: { bi: 30000, ba: 60000, pd: 15000, noFault: false, pip: true, pipMin: 2500, um: true, uim: true, medPay: false, note: "Policies must include $2,500 of personal injury protection, which the policyholder can waive, and Maryland doesn't limit lawsuits. Uninsured and underinsured motorist coverage must match the 30/60/15 minimums.", sourceUrl: "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gtr&section=17-103&enactments=false", confidence: "high" },
  ME: { bi: 50000, ba: 100000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: true, note: "Maine requires 50/100/25 liability, uninsured and underinsured motorist coverage of at least 50/100, and at least $2,000 per person of medical payments coverage.", sourceUrl: "https://legislature.maine.gov/statutes/29-a/title29-Asec1605-A.html", confidence: "high" },
  MI: { bi: 50000, ba: 100000, pd: 10000, noFault: true, pip: true, pipMin: 50000, um: false, uim: false, medPay: false, note: "Michigan policies default to 250/500 bodily injury, but you can choose 50/100 in writing. $10,000 property damage applies to crashes in other states, and $1 million of property protection insurance covers damage in Michigan. You choose a PIP medical level, from unlimited down to $50,000 (Medicaid enrollees), or opt out with qualifying Medicare.", sourceUrl: "https://www.michigan.gov/autoinsurance/frequently-asked-questions", confidence: "high" },
  MN: { bi: 30000, ba: 60000, pd: 10000, noFault: true, pip: true, pipMin: 40000, um: true, uim: true, medPay: false, note: "Minnesota requires $40,000 of personal injury protection ($20,000 medical and $20,000 non-medical), plus separate uninsured and underinsured motorist coverage of at least 25/50 each.", sourceUrl: "https://www.revisor.mn.gov/statutes/cite/65B.49/pdf", confidence: "high" },
  MO: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of 25/50 is mandatory. Underinsured motorist coverage is optional.", sourceUrl: "https://revisor.mo.gov/main/OneSection.aspx?section=303.190", confidence: "high" },
  MS: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured and underinsured motorist coverage is included unless you reject it in writing.", sourceUrl: "https://www.mid.ms.gov/mississippi-insurance-department/consumers/auto-insurance/", confidence: "high" },
  MT: { bi: 25000, ba: 50000, pd: 20000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured and underinsured motorist coverage must be offered and can be rejected.", sourceUrl: "https://mca.legmt.gov/bills/mca/title_0610/chapter_0060/part_0010/section_0030/0610-0060-0010-0030.html", confidence: "high" },
  NC: { bi: 50000, ba: 100000, pd: 50000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "North Carolina raised its minimums from 30/60/25 to 50/100/50 for policies issued or renewed on or after July 1, 2025. Underinsured motorist coverage became mandatory at the same time; uninsured motorist coverage was already required.", sourceUrl: "https://www.ncdoi.gov/changes-rating-automobile-insurance-policies-effective-july-1-2025", confidence: "high" },
  ND: { bi: 25000, ba: 50000, pd: 25000, noFault: true, pip: true, pipMin: 30000, um: true, uim: true, medPay: false, note: "North Dakota requires $30,000 of no-fault personal injury protection per person, plus uninsured and underinsured motorist coverage of 25/50 each.", sourceUrl: "https://www.insurance.nd.gov/consumers/insurance/auto", confidence: "high" },
  NE: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "Uninsured and underinsured motorist coverage of at least 25/50 is mandatory.", sourceUrl: "https://nebraskalegislature.gov/laws/statutes.php?statute=44-6408", confidence: "high" },
  NH: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: true, optional: true, note: "New Hampshire doesn't require car insurance, but you must be able to pay for damage you cause (25/50/25) after an at-fault crash. If you buy a policy, it must include at least $1,000 of medical payments coverage and uninsured motorist coverage equal to your liability limits.", sourceUrl: "https://mm.nh.gov/files/uploads/nhid/documents/nh-auto-guide.pdf", confidence: "high", caveat: "RSA 264:15 only mentions uninsured motorists, so underinsured is set to not required." },
  NJ: { bi: 35000, ba: 70000, pd: 25000, noFault: true, pip: true, pipMin: 15000, um: true, uim: true, medPay: false, note: "New Jersey is a choice no-fault state. Standard Policy minimums rose to 35/70/25 for policies issued on or after January 1, 2026, with at least $15,000 of personal injury protection and uninsured/underinsured motorist coverage. A lower-cost Basic Policy with different limits is also available.", sourceUrl: "https://www.nj.gov/dobi/bulletins/blt25_06.pdf", confidence: "high" },
  NM: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured and underinsured motorist coverage is included unless you reject it in writing.", sourceUrl: "https://www.mvd.newmexico.gov/chapter-11-mandatory-insurance/", confidence: "high" },
  NV: { bi: 25000, ba: 50000, pd: 20000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Nevada has no grace period for lapsed coverage. Uninsured and underinsured motorist coverage must be offered.", sourceUrl: "https://dmv.nv.gov/insurance.htm", confidence: "high" },
  NY: { bi: 25000, ba: 50000, pd: 10000, noFault: true, pip: true, pipMin: 50000, um: true, uim: false, medPay: false, note: "New York liability must also cover 50/100 for death. $50,000 of no-fault personal injury protection and uninsured motorist coverage of 25/50 are mandatory.", sourceUrl: "https://www.dfs.ny.gov/faqs/consumer-auto/how-much-auto-insurance-must-i-carry", confidence: "high" },
  OH: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "A $30,000 bond can be used instead of a policy. Uninsured and underinsured motorist coverage is optional.", sourceUrl: "https://codes.ohio.gov/ohio-revised-code/section-4509.51", confidence: "high" },
  OK: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Insurers must offer uninsured and underinsured motorist coverage of at least 25/50. It isn't mandatory, but it's included until you decline it in writing.", sourceUrl: "https://www.oid.ok.gov/uninsured-motorist/", confidence: "high" },
  OR: { bi: 25000, ba: 50000, pd: 20000, noFault: false, pip: true, pipMin: 15000, um: true, uim: true, medPay: false, note: "Oregon requires $15,000 of personal injury protection per person and uninsured motorist coverage of 25/50 that includes underinsured protection. It doesn't limit lawsuits.", sourceUrl: "https://www.oregonlegislature.gov/bills_laws/ors/ors806.html", confidence: "high" },
  PA: { bi: 15000, ba: 30000, pd: 5000, noFault: true, pip: true, pipMin: 5000, um: false, uim: false, medPay: false, note: "Pennsylvania is a choice no-fault state: $5,000 of first-party medical benefits is mandatory, and you choose limited tort or full tort (full tort is the default). Uninsured and underinsured motorist coverage must be offered but can be rejected.", sourceUrl: "https://www.pa.gov/agencies/insurance/consumer-help-center/learn-about-insurance/auto-insurance", confidence: "high" },
  RI: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "A $75,000 combined single limit can also meet the liability requirement. Uninsured and underinsured motorist coverage equal to your liability limits must be offered, and you can only reject it if you choose minimum limits.", sourceUrl: "https://webserver.rilegislature.gov/Statutes/TITLE31/31-32/31-32-24.htm", confidence: "high" },
  SC: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of 25/50/25 is mandatory, usually with a $200 property damage deductible. Underinsured motorist coverage must be offered but is optional.", sourceUrl: "https://doi.sc.gov/588/Automobile-Insurance", confidence: "high" },
  SD: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "Uninsured motorist coverage is required on all policies, and underinsured motorist coverage must equal your bodily injury limits.", sourceUrl: "https://dlr.sd.gov/insurance/general_guidance/auto.aspx", confidence: "high" },
  TN: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "A $65,000 combined single limit is also accepted. Uninsured motorist coverage is included unless you reject it in writing.", sourceUrl: "https://www.tn.gov/revenue/title-and-registration/drive-insured-tennessee/why-you-should-have-insurance.html", confidence: "high" },
  TX: { bi: 30000, ba: 60000, pd: 25000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Texas policies include personal injury protection ($2,500 minimum) and uninsured/underinsured motorist coverage unless you reject them in writing.", sourceUrl: "https://statutes.capitol.texas.gov/GetStatute.aspx?Code=TN&Value=601.052", confidence: "high" },
  UT: { bi: 30000, ba: 65000, pd: 25000, noFault: true, pip: true, pipMin: 3000, um: false, uim: false, medPay: false, note: "Utah raised its minimums from 25/65/15 to 30/65/25 (or a $90,000 combined single limit) for policies issued or renewed on or after January 1, 2025. $3,000 of personal injury protection is required.", sourceUrl: "https://le.utah.gov/xcode/Title31A/Chapter22/31A-22-S304.html", confidence: "high" },
  VA: { bi: 50000, ba: 100000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "Virginia raised its minimums from 30/60/20 to 50/100/25 on January 1, 2025, and insurance has been mandatory for everyone since July 1, 2024. Uninsured and underinsured motorist coverage at the minimum limits is required.", sourceUrl: "https://law.lis.virginia.gov/vacode/title46.2/chapter3/section46.2-472/", confidence: "high" },
  VT: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: false, pipMin: null, um: true, uim: true, medPay: false, note: "Vermont requires uninsured and underinsured motorist coverage at higher limits than liability: 50/100 for injuries and $10,000 for property damage.", sourceUrl: "https://legislature.vermont.gov/statutes/section/23/011/00941", confidence: "high" },
  WA: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Personal injury protection and uninsured/underinsured motorist coverage must be offered and can be rejected in writing.", sourceUrl: "https://www.insurance.wa.gov/insurance-resources/auto-insurance/how-auto-insurance-works/washington-states-mandatory-automotorcycle-insurance-law", confidence: "high" },
  WI: { bi: 25000, ba: 50000, pd: 10000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of 25/50 for injuries is mandatory. Underinsured motorist coverage is optional, and $1,000 of medical payments coverage must be offered.", sourceUrl: "https://oci.wi.gov/Documents/Consumers/PI-233.pdf", confidence: "high" },
  WV: { bi: 25000, ba: 50000, pd: 25000, noFault: false, pip: false, pipMin: null, um: true, uim: false, medPay: false, note: "Uninsured motorist coverage of 25/50 for injuries and $25,000 for property damage is mandatory. Underinsured motorist coverage must be offered but is optional.", sourceUrl: "https://www.wvinsurance.gov/Consumer_Services_mandatory_limits", confidence: "high" },
  WY: { bi: 25000, ba: 50000, pd: 20000, noFault: false, pip: false, pipMin: null, um: false, uim: false, medPay: false, note: "Uninsured motorist coverage must be offered and can be rejected.", sourceUrl: "https://codes.findlaw.com/wy/title-31-motor-vehicles/wy-st-sect-31-10-101/", confidence: "high" },
};

/** The fields to store for a state, from the research. */
export function researchFields(code: string) {
  const r = STATE_RESEARCH[code];
  if (!r) return null;
  return {
    biPerPerson: r.bi,
    biPerAccident: r.ba,
    pd: r.pd,
    noFault: r.noFault,
    pipRequired: r.pip,
    pipMinimum: r.pipMin,
    umRequired: r.um,
    uimRequired: r.uim,
    medPayRequired: r.medPay,
    insuranceOptional: !!r.optional,
    requirementNote: r.note,
    sourceUrl: r.sourceUrl,
  };
}
